spring:
  application:
    name: ms-discovery

server:
  port: 8761

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://172.20.0.4:${server.port}/eureka/

# this 172.20.0.1 is from the docker network